"""initial_schema

Revision ID: 9f27a983fe62
Revises: 
Create Date: 2026-07-21 22:43:15.436381
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9f27a983fe62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_tier', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('prompt_versions',
    sa.Column('prompt_id', sa.String(length=64), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_model', sa.String(length=128), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('forbid_list', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('resume_sources',
    sa.Column('resume_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.Enum('PDF', 'TEXT', 'LATEX', name='sourcetype'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('interviews',
    sa.Column('interview_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('resume_id', sa.String(length=64), nullable=False),
    sa.Column('target_role', sa.String(length=256), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_sources.resume_id'], ),
    sa.PrimaryKeyConstraint('interview_id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_table('resume_claims',
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('resume_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_sources.resume_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('resume_revisions',
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('resume_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSED_UNCONFIRMED', 'CONFIRMED', 'SUPERSEDED', 'FAILED', name='resumestatus'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('PDF_TEXT', 'PLAIN_TEXT', 'LATEX_STATIC', name='extractionmethod'), nullable=True),
    sa.Column('extraction_quality', sa.Float(), nullable=True),
    sa.Column('extraction_warnings', sa.JSON(), nullable=True),
    sa.Column('parser_name', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_sources.resume_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_table('interview_questions',
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('interview_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('interview_reports',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('interview_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('interview_id')
    )
    op.create_table('resume_blocks',
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('block_type', sa.Enum('HEADING', 'ENTRY_HEADER', 'PARAGRAPH', 'BULLET', 'CONTACT', 'UNKNOWN', name='blocktype'), nullable=False),
    sa.Column('source_location', sa.JSON(), nullable=True),
    sa.Column('style_hints', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['resume_revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('resume_profiles',
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('resume_id', sa.String(length=64), nullable=False),
    sa.Column('revision_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_sources.resume_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['resume_revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('interview_answers',
    sa.Column('answer_id', sa.String(length=64), nullable=False),
    sa.Column('interview_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_answers')
    op.drop_table('resume_profiles')
    op.drop_table('resume_blocks')
    op.drop_table('interview_reports')
    op.drop_table('interview_questions')
    op.drop_table('resume_revisions')
    op.drop_table('resume_claims')
    op.drop_table('interviews')
    op.drop_table('resume_sources')
    op.drop_table('prompt_versions')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
